export const NAVIGATION_ROUTES = {
  DASHBOARD: "/",
  LOGIN: "/login",
  SERVICES: "/services",
  ADVERTISEMENT: "/advertisement",
  FAQ: "/FAQ",
  FAQ_CREATE: "/FAQ/create",
  FORUM: "/forum",
  ABOUT_US: "/about-us",
  NOTIFICATION: "/notification",
  PREMIUM_AD: "/permium-ad",
  ADVANCE_AD: "/advance-ad",
  COURSES: "/services/course",
  SUBJECTS: "/services/subjects",
  QUESTION_SET: "/services/subjects/question-set",
  MODEL_SET: "/services/CMAT/model-set",
  CREATE_QUESTION_SET: "/services/CMAT/question-set/create",
  ABROAD_STUDIES: "/services/abroad-studies",
  BASIC_AD: "/basic-ad",
  SETTINGS: "/settings",
  LOGOUT: "./logout",
};
