export const NAVIGATION_ROUTES = {
  DASHBOARD: "/",
  LOGIN: "/login",
  SERVICES: "/services",
  ADVERTISEMENT: "/advertisement",
  FAQ: "/FAQ",
  FAQ_CREATE: "/FAQ/create",
  FORUM: "/forum",
  FORUM_ANSWER: "/forum/answer",
  ABOUT_US: "/about-us",
  NOTIFICATION: "/notification",
  PREMIUM_AD: "/permium-ad",
  ADVANCE_AD: "/advance-ad",
  COURSES: "/services/course",
  FORM: "/services/form",
  NON_QUESTIONNAIRE: "/services/non-questionnaire",
  SUBJECTS: "/services/subjects",
  QUESTION_SET: "/services/question-set",
  MODEL_SET: "/services/model-set",
  CREATE_QUESTION_SET: "/services/question-set-create",
  VIEW_QUESTION_SET: "/services/question-set-view",
  VIEW_QUESTION: "/services/question",
  ABROAD_STUDIES: "/services/abroad-studies",
  BASIC_AD: "/basic-ad",
  SETTINGS: "/settings",
  ROLES: "/roles",
  CONTACT_US: "/contact",
  // LOGOUT: "./logout",
};
